name: Build

on:
  push:
    branches: 
      - main
    tags:
      - '*'

env:
  DOTNET_VERSION: '6.0.x'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: dotnet publish --configuration Release --output ./publish
      #  -r linux-x64 --self-contained true /p:UseAppHost=true

    - name: 'Zip binaries'
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ./function.zip ./publish/

    - name: Publish Tags
      uses: "marvinpinto/action-automatic-releases@latest"
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: ./function.zip