# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build

on:
  push:
    branches: 
      - main
    tags:
      - 'v*'

env:
  DOTNET_VERSION: '6.0.x'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: dotnet publish --configuration Release --output ./publish
      #  -r linux-x64 --self-contained true /p:UseAppHost=true

    - name: 'Zip binaries'
      uses: papeloto/action-zip@v1
      with:
        dest: function.zip
        files: publish/*
        recursive: true

    - name: Publish Tags
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        artifacts: ./function.zip